services:
  mongo:
    image: mongo:7
    container_name: dicom_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dicom
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    container_name: dicom_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dicom
      POSTGRES_PASSWORD: dicom
      POSTGRES_DB: dicom_meta
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mongo_data:
  pg_data:
